print("please enter the following information, with no repetition:")
print()

adjective = input("Adjective:")
animal = input("Animal:")
verb_1 = input("Verb:")
exclamation = input("Exclamation:")
verb_2 = input("Verb:")
verb_3 = input("Verb:")
verb_4 = input("Verb:")
verb_5 = input("Verb:")

# Print the story
print("Your story is:")
print("")
print("The other day, I was really in trouble. It all started when I saw a very")
print(f"{adjective.lower()} {animal.lower()} {verb_1.lower()} down the hallway.{exclamation.capitalize()}! I yelled. But all")
print(f"I could think to do was to {verb_2.lower()} over and over. Miraculously,")
print(f"that caused it to stop, but not before it tried to {verb_3.lower()}")
print(f"right in front of my family. Suddenly, everyone started to {verb_4.lower()} as fast as they could.")
print(f"In the end, we all just {verb_5.lower()} until the whole thing seemed like a wild dream.")